apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.nodePort }}
