{{- if .Values.Ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  namespace: chatapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" 
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.Ingress.host | default "localhost" }} 
      http:
        paths:
          - path: /
            pathType: Prefix  
            backend:
              service:
                name: {{ .Values.frontend.name }} 
                port:
                  number: 3000  
          - path: /api
            pathType: Prefix  
            backend:
              service:
                name: {{ .Values.backend.name }} 
                port:
                  number: 5000
{{- end -}}
